### ISSUE TITLE
Tracking issue: Tact v1.4.0

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tree-sitter-tact#32]
To be covered by #33:
- [x] Bitwise NOT `~`
- [x] New augmented assignment operators: `|=`, `&=`, `^=`
- [x] Optional `;` in field declarations of Structs and Messages
- [x] Constant string receivers
- [x] Local type inference for `let` statements (optional type ascription)
- [x] Optional `;` for the last statement in a block: [tact-lang/tact#434](https://github.com/tact-lang/tact/pull/434)
- [x] foreach over lvalues and not just identifiers
- [x] nativeThrowWhen renamed to nativeThrowIf

Other things:
- [x] Small refactoring of names and structure (leave no TODOs)
- [x] Tests and queries, lot's of 'em!
- [x] Make a new v1.4.0 release on GitHub
 
Optional, due to potential issues with query performance (better add those later in semantic highlighting from LSP):
- Underscores `_` as unused variable identifiers (highlighting-only, and with narrowed captures)
- Identifiers starting with `__gen` or `__tact`

**Comment by novusnota** [comment]
All the things related to 1.4.0 are done, so this will be closed. All the miscellaneous things related to 1.4.1 and PRs with new queries are moved to #37
