### ISSUE TITLE
Tracking issue: Tact v1.4.1

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tree-sitter-tact#37]
- [x] Fix FunC identifiers regex/recognition, see https://github.com/tact-lang/tact/issues/627
- [x] Do smaller updates related to 1.4.1 version (bugfix release): #36
- [x] Make a PR to Neovim repo's with new queries:
  - [x] nvim-treesitter
    - for 1.4.0, graciously done by clason: https://github.com/nvim-treesitter/nvim-treesitter/pull/6808
    - for 1.4.1: https://github.com/nvim-treesitter/nvim-treesitter/pull/7075
  - [x] nvim-treesitter-textobjects: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/642
  - [x] nvim-treesitter-context: https://github.com/nvim-treesitter/nvim-treesitter-context/pull/459
- [x] Make a PR to Helix in the reversed-queries branch (postpone that until subsequent releases)
- [x] Make a 1.4.1 release on Github
