### ISSUE TITLE
Milestone Tact v1.3.0

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tree-sitter-tact#8]
This is a tracking issue towards matching Tact v1.3.0: https://github.com/tact-lang/tact/issues/280

Parser: https://github.com/tact-lang/tree-sitter-tact/releases/tag/v1.3.0
- [x] Parser matches Tact version 1.3.0
- [x] All Tree-sitter queries are updated
- [x] All old and new tests pass

PRs to Neovim:
  - [x] `nvim-treesitter`: https://github.com/nvim-treesitter/nvim-treesitter/pull/6554
  - [x] `nvim-treesitter-textobjects`: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/609
  - [x] `nvim-treesitter-context`: https://github.com/nvim-treesitter/nvim-treesitter-context/pull/436

**Comment by novusnota** [comment]
As an aside, started working on major Emacs mode (i.e. plugin) for Tact after the last poll in the dev community. It would largely consist of: tree-sitter-tact integration and inclusion of upcoming LSP (both extracted and planned :)

**Comment by novusnota** [comment]
> As an aside, started working on major Emacs mode (i.e. plugin) for Tact after the last poll in the dev community. It would largely consist of: tree-sitter-tact integration and inclusion of upcoming LSP (both extracted and planned :)

Postponed the finalization of that project until Tact/TON has more Emacs users. Existing queries for tree-sitter should just work for Emacs prior to version 29 and the existing [extracted LS](https://github.com/novusnota/tact-extracted-ls) should be easy to bind on any Emacs having an Eglot or LSP-mode.

Prioritizing making a nice Sublime Text package now!

**Comment by novusnota** [comment]
And with adding support to Neovim, this is now completed! Now all users of Neovim won't have to configure anything beyond installing tree-sitter plugin there and getting highlighting, indentation, sticky contexts, various selections and more out of the box once they open any .tact file :tada:
